### ISSUE TITLE
PHP 7.1 Support

### ISSUE THREAD

**Issue by apsylone** [phpmentors-jp/docker-images#30]
Hi PHP Mentors :-)

I'm using your docker images everyday. And thank you for this !
I've tried to add a PHP 7.1 support but it seems that it is something more complicated than I think.

Do you think it will possible for you to add this ?

Doctrine and so others libs uses "void" and some other keywords.

Thanks, hope you'll help me :-)

**Comment by iteman** [comment]
PHP 7.1 has now been supported by `phpmentors/php-app:php71` and `phpmentors/symfony-app:php71` :smile:
